[package]
name = "ferrum_engine"
description = "A tiny little database engine project powered by Rust."
version = "0.2.0"
edition = "2024"
authors = ["Taimoor Ikram <taimoorikram01@gmail.com>"]

[dependencies]
colored = "3.0.0"
log = "0.4.29"
